### ISSUE TITLE
POST_SCRIPT example

### ISSUE THREAD

**Issue by oussemos** [pdellaert/vSphere-Python#10]
Can you please add a post script example?
I want to assign an IP address to the VM created!
Thanks

**Comment by pdellaert** [comment]
If you have DHCP running, your VMs will get an IP through DHCP, which the multi-clone script can read out. It can call the post script with that as one of the parameters. 

Inside the post script you can then for instance SSH into the VM and change the configuration with SSH commands.

Setting the IP without network connectivity is not supported at the moment. The Post script is executed on the machine where you run the multi-clone script.
