### ISSUE TITLE
Set Affinity rule on a particular VM to stop DRS

### ISSUE THREAD

**Issue by rreubenur** [pdellaert/vSphere-Python#2]
Hi ,

Would you please me help me to achieve that. After cloning I want to set affinity rule for that new vm to stop DRS.

+pyVmomi

Thanks,
Reuben

**Comment by pdellaert** [comment]
I seem to have missed this, i'm sorry... I'll try and look into this in the near future (al thou i'm pretty busy these next weeks). 

I assume you mean a VM-host affinity rule?
Would you want all clones to be linked to the same host?

**Comment by rreubenur** [comment]
The requirement was different and the question was different :) We had to make a vm sticky for the particular host so that drs or ha can't move it. creating a rule for all vms seems bad idea but I have accomplished it with the ```vim.cluster.DasVmSettings.RestartPriority.disabled ```

**Comment by pdellaert** [comment]
Oh, ok :). In that case i'm closing this one. Thanks for the update!
